on:
  push:
    branches:
      - main  # Adjust to your branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Remix App to OVH Hosting

    steps:
      # Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.14.0'  # Adjust to your Node.js version

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Build Remix app
      - name: Build Remix App
        run: npm run build

      # Deploy to OVH Hosting
      - name: Deploy to OVH Hosting
        uses: pitscher/ovh-deploy-hosting-action@v1
        env:
          OVH_HOSTING_USER: guillak
          OVH_HOSTING_PASSWORD: Aqwzsxedc123
          OVH_HOSTING_DOMAIN: ssh.cluster021.hosting.ovh.net
          REPOSITORY_NAME: portfolio
          REPOSITORY_URL: https://github.com/Titancki/portfolio.git