on:
  push:
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Guillaume Ouf
    steps:
      - name: Deploy to OVH hosting
        uses: pitscher/ovh-deploy-hosting-action@v1
        env:
          OVH_HOSTING_USER: ${{ secrets.guillak }}
          OVH_HOSTING_PASSWORD: ${{ secrets.Aqwzsxedc123 }}
          OVH_HOSTING_DOMAIN: ssh.cluster021.hosting.ovh.net
          REPOSITORY_NAME: portfolio
          REPOSITORY_URL: https://github.com/me/my-repo.git